config/routes.rb
BenchmarkingDemo::Application.routes.draw do

  match "update" => 'company#update', :as => 'update'
  match "benchmark" => 'company#benchmark', :as => 'benchmark'
  match "browse" => 'company#browse', :as => 'browse'
  root :to => redirect('/browse')

end

app/models/company.rb
# Copyright (C) 2011 AMEE UK Ltd. - http://www.amee.com
# Released as Open Source Software under the BSD 3-Clause license. See LICENSE.txt for details.

class Company

  STANDARD_DECIMAL_PLACES = nil

  INTENSITY_DECIMAL_PLACES = 7

  def self.is_non_numeric_attribute?(attr)
    [ "@company", "@sector", "@country", "@financial_metric" ].include?(attr.to_s)
  end

  def self.is_intensity_attribute?(attr)
    attr.to_s == "@mass_co2e_per_usd_financial_metric"
  end

  attr_accessor :name
  attr_accessor :sector
  attr_accessor :country
  attr_accessor :financial_metric
  attr_accessor :total_financial_metric_usd
  attr_accessor :mass_scope_one_co2e
  attr_accessor :mass_scope_two_co2e
  attr_accessor :mass_co2e_per_usd_financial_metric 
  attr_accessor :energy_scope_one
  attr_accessor :energy_scope_two_total
  attr_accessor :energy_scope_two_electricity

  def initialize(options={})
    options.each do |key,value|
      self.instance_variable_set("@#{key.underscore}".to_sym, value)
    end
    round_attributes
  end

  def name
    @company
  end

  def total_emissions
    @mass_scope_one_co2e.to_f + @mass_scope_two_co2e.to_f
  end

  def round_attributes
    self.instance_variables.each do |ivar|
      next if Company.is_non_numeric_attribute?(ivar) 
      self.instance_variable_set(ivar, round_attribute(ivar))
    end
  end

  def round_attribute(ivar)
    decimal_places = Company.is_intensity_attribute?(ivar) ? INTENSITY_DECIMAL_PLACES : STANDARD_DECIMAL_PLACES
    self.instance_variable_get(ivar).to_f.round(decimal_places)
  end

end

app/controllers/company_controller.rb
# Copyright (C) 2011 AMEE UK Ltd. - http://www.amee.com
# Released as Open Source Software under the BSD 3-Clause license. See LICENSE.txt for details.

class CompanyController < ApplicationController

  before_filter :generate

  def benchmark; end

  def browse; end

  def update; end

  def generate
    
    @company_set = CompanySet.new(params)

    if @company_set.search_term?

      @company_set.filter_by_search_term
      @chart = true unless @company_set.selected.empty? || @company_set.all?

    else

      @company_set.filter

      if @company_set.selected.size > 0

        @company_set.normalize! if @company_set.financial_measure
        
        @company_set.append_average_sector_representation if @company_set.sector

        @company_set.append_custom_company_representation if @company_set.has_custom_company_data?

        @company_set.normalize_grid! if @company_set.country_for_grid_normalization

      end

      if @company_set.valid_selections? && @company_set.selected.size > 0 && !@company_set.all?

        @company_set.sort! 
        @chart = true
       
      end
    end
  end

end

app/helpers/company_helper.rb
# Copyright (C) 2011 AMEE UK Ltd. - http://www.amee.com
# Released as Open Source Software under the BSD 3-Clause license. See LICENSE.txt for details.

module CompanyHelper

  def column_chart(set) # added argument as precursor to abstracting this out to a view helper
    data_table = GoogleVisualr::DataTable.new
    data_table.new_column('string', 'Company')
    data_table.new_column('number', 'CO2e (t)')
    data_table.new_column('number', 'CO2e (t)')
    data_table.new_column('number', 'CO2e (t)')
    data_table.add_rows(set.selected.size)
    set.selected.each_with_index do |selection,index|
      data_table.set_cell(index, 0, selection.name)
      if selection.name == 'My Company'
        data_table.set_cell(index, 1, 0)
        data_table.set_cell(index, 2, selection.total_emissions)
        data_table.set_cell(index, 3, 0)
      elsif selection.name == 'Sector average'
        data_table.set_cell(index, 1, 0)
        data_table.set_cell(index, 2, 0)
        data_table.set_cell(index, 3, selection.total_emissions)
      else
        data_table.set_cell(index, 1, selection.total_emissions)
        data_table.set_cell(index, 2, 0)
        data_table.set_cell(index, 3, 0)
      end
    end

    options = chart_formatting_options
    options[:title] = chart_title(set)

    chart = GoogleVisualr::Interactive::ColumnChart.new(data_table, options)
    chart.add_listener(:select,chart_select_callback)
    return chart
  end

  def chart_title(set)
    if set.normalized? && set.grid_normalized?
      "Scopes 1 and 2 emissions normalized to company #{set.financial_metric.downcase} and grid intensity"
    elsif set.grid_normalized?
      "Scopes 1 and 2 emissions normalized to grid intensity"
    elsif set.normalized?
      "Scopes 1 and 2 emissions normalized to company #{set.financial_metric.downcase}"
    else
      "Disclosed scopes 1 and 2 emissions by company"
    end
  end

  def chart_formatting_options
  	{ :width => 980,
      :height => 300,
      :titlePosition => 'out',
      :titleTextStyle => { :color => '#525252'},
      :colors =>  ['#79afff','#33CC66','#5e5e5e'],
      :chartArea => { :width => 800, :left => 150, :top => 70 },
      :vAxis => { :title => 'CO2e (tonnes)',
                  :titleTextStyle => {:color => '#525252'}},
      :hAxis => { :textPosition => 'in',
                  :slantedText => 'true',
                  :slantedTextAngle => 90,
                  :maxAlternation => 4 },
      :legend => 'none',
      :backgroundColor => { :stroke => '#79afff'},
      :enableInteractivity => 'true',
      :isStacked => 'true'
    }
  end

  def chart_select_callback
  	js  = "\nfunction(){"
  	js << "\n  cell = chart.getSelection()[0];"
  	js << "\n  value = data_table.getFormattedValue(cell.row,0);"
  	js << "\n  scrollToCompany(value.toLowerCase().replace(/ /g,'-'));"
  	js << "\n}"
  	js
  end

end

app/views/company/_benchmark_panel.html.erb
<div  id="benchmark-form-wrapper" class="content_pane">
    <%= form_tag(benchmark_path, :method => 'get') do %>
    <table>
      <tr class="benchmark-select">
        <td>Choose a sector</td>
        <td><%= select_tag 'sector', options_for_select(CompanySet.sector_list.reject {|s| s == 'All'}, @company_set.sector) %></td>
      </tr>
      <tr class="benchmark-text">
        <td>Set scope 1 emissions</td>
        <td><span><%= text_field_tag 'mass_scope_one_co2e', @company_set.mass_scope_one_co2e %></span><span> Metric tonnes (t)</span></td>
      </tr>
      <tr class="benchmark-text">
        <td>Set scope 2 emissions</td>
        <td><span><%= text_field_tag 'mass_scope_two_co2e', @company_set.mass_scope_two_co2e %></span><span> Metric tonnes (t)</span></td>
      </tr>
      <tr class="benchmark-text">
        <td>Set scope 1 energy consumption</td>
        <td><span><%= text_field_tag 'energy_scope_one', @company_set.energy_scope_one %></span><span> Megawatt hours (MWh)</span></td>
      </tr>
      <tr class="benchmark-text">
        <td>Set scope 2 energy consumption</td>
        <td><span><%= text_field_tag 'energy_scope_two_total', @company_set.energy_scope_two_total %></span><span> Megawatt hours (MWh)</span></td>
      </tr>
      <tr class="benchmark-select">
        <td>Choose a financial metric</td>
        <td><%= select_tag 'financial_metric', options_for_select(CompanySet.financial_metric_list.reject {|s| s == 'All'}, @company_set.financial_metric || 'Revenue') %></td>
      </tr>
      <tr class="benchmark-text">
        <td>Set a financial benchmark</td>
        <td><span><%= text_field_tag 'financial_measure', @company_set.financial_measure %></span><span> USD ($)</span></td>
      </tr>
      <tr class="benchmark-text">
        <td>Normalize grid electricity</td>
        <td><%= select_tag 'country_for_grid_normalization', options_for_select(AMEE::Electricity.country_choices, @company_set.country_for_grid_normalization || 'None') %></td>
      </tr>
    </table>
    <div id="benchmark-submit">
      <%= submit_tag 'Benchmark!' %>
    </div>
    <% end %>
  </div>
  <div id="chart" class="content_pane">
    <%= render :partial => 'chart' %>
  </div>

app/views/company/_benchmark_scripts.html.erb
<% content_for :head do %>

<script src='http://www.google.com/jsapi'></script>

  <%= javascript_tag do %>

    $(document).ready(function(){

      filters$ = $("table#filter td select");
      
      filters$.live('change', function(){
        tableLoading();
        updateTableAndChart($(this).attr('id') + "=" + $(this).attr('value').replace(/&/g, "%26"));
      });

      $('#q').live('keyup', function(){
        query = "q=" + $(this).attr('value').replace(/&/g, "%26");
        // Use timer property to ensure multiple requests are not made in quick succession
        var timer = $(this).data('timer');
        if(timer) {
          clearTimeout(timer);
        }
        tableLoading();
        $(this).data('timer', setTimeout("updateTableAndChart(query);", 300));
        
      });

      manageTableStyle();
      manageAddedRows();

    });

    function tableLoading() {
      row$ = $("table#benchmark tbody tr:first");
      rows$ = $("table#benchmark tbody").children("tr:gt(0)");
      cells$ = row$.children("td").not(".dummy");

      rows$.remove();
      $("table#benchmark th.dummy").width("0px");

      renderLoadingGif(cells$);
    }

    function updateTableAndChart(query) {
      jQuery.ajax({
        data:     query,
        dataType: 'script',
        type:     'post',
        url:      '/update'
      });
    }

    function manageTableStyle() {
      tableRowBackgroundColor($("table#benchmark tbody tr:odd"), '#f0f0ff');
      tableRowBackgroundColor($("table#benchmark tbody tr:even"), 'White');

      tableHeaderWidth();

    }

    function manageAddedRows() {
      $("table#benchmark tbody tr#my-company").children("td").each(function(){
          $(this).css('background',"#33CC66").css('color', 'White');
      });

      $("table#benchmark tbody tr#sector-average").children("td").each(function(){
          $(this).css('background',"#5e5e5e").css('color', 'White');
      });

      scrollToCompany("my-company");
    }

    function scrollToCompany(name) {
      container = $("table#benchmark tbody");
      height = container.height();
      contentHeight = container.prop('scrollHeight');
      if (contentHeight > height) {
        row = $("table#benchmark tbody tr#"+name);
        position = row.position();
        if (typeof(position) != 'undefined') {
          container.animate({scrollTop: position.top-(height/2)}, 2000);
        }
      }
    }

    function tableRowBackgroundColor(rows,color) {
      $(rows).each(function() {
        cells$ = $(this).children("td");
        cells$.each(function(){
          $(this).css('background',color);
        });
      });
    }

    function tableHeaderWidth() {
      tableBody$ = $("table#benchmark > tbody");
      dummyCell$ = $("table#benchmark th.dummy");
      if (tableBody$.height() == 280) {
        dummyCell$.width("28px");
      } else {
        dummyCell$.width("0px");
      }

    }

  <% end %>    
<% end %>

app/views/company/_blank_row.html.erb
<tr>
  <td class="text company">No matches</td>
  <td class="text country">&nbsp;</td>
  <td class="text sector">&nbsp;</td>
  <td class="number scope-1-emissions">&nbsp;</td>
  <td class="number scope-2-emissions">&nbsp;</td>
  <td class="number scope-1-energy">&nbsp;</td>
  <td class="number scope-2-energy">&nbsp;</td>
  <td class="text metric">&nbsp;</td>
  <td class="number intensity">&nbsp;</td>
  <td class="dummy"></td>
</tr>

app/views/company/_browse_panel.erb
<div  id="benchmark-form-wrapper" class="content_pane">
  <table id="filter">
    <tr>
      <td>Filter by:</td>
    </tr>
    <tr>
      <td>Sector:</td><td> <%= select_tag 'sector', options_for_select(CompanySet.sector_list, @company_set.sector || "All") %></td>
    </tr>
    <tr>
      <td>Country:</td><td> <%= select_tag 'country', options_for_select(CompanySet.country_list, @company_set.country || "All") %></td>
    </tr>
    <tr>
      <td>Financial metric:</td><td> <%= select_tag 'financial_metric', options_for_select(CompanySet.financial_metric_list, @company_set.financial_metric || "All") %></td>
    </tr>
    <tr>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>Search</td><td style="color: LightGray">start typing . . .</td>
    </tr>
    <tr>
      <td>Company:</td><td><%= text_field_tag 'q' %></td>
    </tr>
  </table>
</div>
<div id="chart" class="content_pane">
  <%= render :partial => 'chart' %>
</div>

app/views/company/_chart.html.erb
<% if @chart %>
  <% chart = column_chart(@company_set) %>
  <%= render_chart(chart,'chart') %>
<% else %>
  <%= image_tag "AMEE-Logo2011-LINE_Green.png" %>
<% end %>

app/views/company/_company_table.html.erb
<span class="ajaxloader" style="display:none;"><%= image_tag 'loading_small.gif' %></span>

<table id="benchmark">
  <thead>
    <tr>
      <th class="company">Company</th>
      <th class="country">Country</th>
      <th class="sector">Sector</th>
      <th class="scope-1-emissions">Scope 1 (t)</th>
      <% if @company_set.grid_normalized? %>
        <th class="scope-2-emissions">Scope 2 electricity only (t)</th>
      <% else %>
        <th class="scope-2-emissions">Scope 2 (t)</th>
      <% end %>
      <th class="scope-1-energy">Scope 1 (MWh)</th>
      <% if @company_set.grid_normalized? %>
        <th class="scope-2-energy">Scope 2 electricity only (MWh)</th>
      <% else %>
        <th class="scope-2-energy">Scope 2 (MWh)</th>
      <% end %>
      <th class="metric">Financial metric</th>
      <th class="intensity">kg CO2e per $</th>
      <th class="dummy"></th>
    </tr>
  </thead>
  <tbody>
    <% if @company_set.selected.empty? %>
      <%= render :partial => 'blank_row' %>
    <% else %>
      <% @company_set.selected.each do |company| %>
        <tr id="<%= company.name.downcase.gsub(" ","-") %>">
          <td class="text company"><%= company.name %></td>
          <td class="text country"><%= company.country %></td>
          <td class="text sector"><%= company.sector %></td>
          <td class="number scope-1-emissions"><%= company.mass_scope_one_co2e.to_s %></td>
          <td class="number scope-2-emissions"><%= company.mass_scope_two_co2e.to_s %></td>
          <td class="number scope-1-energy"><%= company.energy_scope_one.to_s %></td>
          <% if @company_set.grid_normalized? && company.energy_scope_two_electricity %>
            <td class="number scope-2-energy"><%= company.energy_scope_two_electricity.to_s %></td>
          <% else %>
            <td class="number scope-2-energy"><%= company.energy_scope_two_total.to_s %></td>
          <% end %>
          <td class="text metric"><%= company.financial_metric %></td>
          <% if company.mass_co2e_per_usd_financial_metric.blank? %>
            <% value = company.mass_co2e_per_usd_financial_metric %>
          <% else %>
            <% value  = "%f" % company.mass_co2e_per_usd_financial_metric %>
          <% end %>
          <td class="number intensity"><%= value %></td>
          <td class="dummy"></td>
        </tr>
      <%end%>
    <%end%>
  </tbody>
</table>

app/views/company/benchmark.html.erb
<%= render :partial => 'benchmark_scripts' %>
<div id="upper-pane">
  <%= render :partial => 'benchmark_panel' %>
</div>
<div id="benchmark-wrapper" class="content_pane">
  <div id="benchmark-table-wrapper">
    <% if @company_set.selected %>
      <%= render :partial => 'company_table' %>
    <% else %>
      <%= image_tag 'AMEE-bug-ref_125x125.png', :alt => 'AMEE' %>
    <% end %>
  </div>
</div>
<br/>
<br/>

app/views/company/browse.html.erb
<%= render :partial => 'benchmark_scripts' %>
<div id="upper-pane">
  <%= render :partial => 'browse_panel' %>
</div>
<div id="benchmark-wrapper" class="content_pane">
  <div id="benchmark-table-wrapper">
    <%= render :partial => 'company_table' %>
  </div>
</div>
<br/>
<br/>

app/views/company/update.js.erb
$('#benchmark-table-wrapper').html('<%= escape_javascript(render :partial => 'company_table') %>');
$('#chart').html('<%= escape_javascript(render :partial => 'chart') %>');
manageTableStyle();
<% if @sector_average %>
  manageAddedRows();
<% end %>